#!/bin/bash

# Copyright (C) 2018
# Author: Marco D'Amico (marco.damico@bsc.es)

#SBATCH -J slurm_into_slurm
#SBATCH -o OUTPUTS/test_%j.out
#SBATCH -e OUTPUTS/test_%j.err
#SBATCH --nodes=4
#SBATCH --partition=dp-cn
#SBATCH --exclusive
#SBATCH -t 00:02:00


source slurm_job_startup

#############################
# Launch your workload here #
#     using sbatch/srun     #
#############################
export PMI_DEBUG=1

srun -n 3 -N 3 hostname

source slurm_job_shutdown
