#!/bin/bash

# Copyright (C) 2018
# Author: Marco D'Amico (marco.damico@bsc.es)

echo "waiting for workload to finish"
while [[ $(squeue -h 2> /dev/null | wc -l) > 0 ]] ; do
  sleep 10
done

#moving jobs output files to JOBS_OUTPUT
mkdir $SLURM_USER_PATH/JOBS_OUTPUT/OUTS.$id
mv slurm-*.out $SLURM_USER_PATH/JOBS_OUTPUT/OUTS.$id

echo "Shutting down Slurm"
$SLURM_HOME/bin/scontrol shutdown
sleep 5;
